### ISSUE TITLE
Plugin functionality is broken in 2022

### ISSUE THREAD

**Issue by Exterrastionale** [raitonoberu/plugin.video.2x2#1]
After launch, only "404: Unfortunately, you are unable to watch the video on this website" pop-up appears on the screen.

**Comment by raitonoberu** [comment]
Thanks for reporting, I haven't used the plugin myself for a long time. I'll see what I can do.

**Comment by raitonoberu** [comment]
They added a Referer header check — easily fixed in [v1.1](https://github.com/raitonoberu/plugin.video.2x2/releases/tag/v1.1). Let me know if you encounter any issues.
